apiVersion: v1
kind: Pod
metadata:
  namespace: rvlapp
  name: rvl-app
  labels:
    app: employees
spec:
  containers:
    - name: app-pod
      image: 406947468681.dkr.ecr.us-east-1.amazonaws.com/rvl-app:v1.0
      ports:
        - containerPort: 8080
          protocol: TCP
      env:
       - name: DBHOST
         value: "10.244.0.5"
       - name: DBPORT
         value: "3306"
       - name: DBPWD
         value: "rvl"
       - name: DBUSER
         value: "root"
