apiVersion: v1
kind: Service
metadata:
  namespace: rvldb
  name: cluster-service
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
  selector:
    app: mysql

